<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CouncilorOffice.Domain\CouncilorOffice.Domain.csproj" />
    <ProjectReference Include="..\CouncilorOffice.Proxy\CouncilorOffice.Proxy.csproj" />
  </ItemGroup>

</Project>
