<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Categories.Domain\Categories.Domain.csproj" />
    <ProjectReference Include="..\Categories.Messages\Categories.Messages.csproj" />
    <ProjectReference Include="..\Categories.Proxy\Categories.Proxy.csproj" />
    <ProjectReference Include="..\Common.Domain\Common.Domain.csproj" />
  </ItemGroup>

</Project>
